dist: bionic
os: linux
arch: arm64
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - cmake
      - git
      - build-essential  

script:
  - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 cmake .
  - cmake --build .
  - ctest
