arch: arm64
language: cpp

matrix:
  include:
    - os: linux
    - dist: bionic
    - sudo: true

    - addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-9
          - cmake
          - cmake-data
          - git
          - build-essential

before-install:
  - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 cmake .
  - cmake --build .
  - ctest
