arch: arm64
os: linux
language: cpp
dist: bionic

env:
- BUILD_TYPE=Debug
- BUILD_TYPE=Release

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get upgrade

install:
  - |
    sudo apt-get install g++-9 cmake cmake-data git build-essential 

script:
- |
  mkdir build &&
  cd build &&
  cmake .. -DCMAKE_CXX_COMPILER=g++-9 -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_BUILD_TYPE=${BUILD_TYPE} &&
  cmake --build --config ${BUILD_TYPE} --target full &&
  ctest --config ${BUILD_TYPE}

notifications:
  email: false

