arch: arm64
os: linux
language: cpp
dist: bionic

env:
  - BUILD_TYPE=Debug CC=gcc-9 CXX=g++-9
  - BUILD_TYPE=Release CC=gcc-9 CXX=g++-9

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install g++-9 git build-essential cmake


script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - cmake --build . --config ${BUILD_TYPE} --target full -- -k
  - ctest -C ${BUILD_TYPE} -j1 -VV --timeout 300 

notifications:
  email: false

