name: MacOS

on:
  push:
    branches: [release, develop]
  pull_request:
    push:
      branches-ignore: develop
    pull_request:
      branches-ignore: develop

jobs:
  debug17:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: ./ci_scripts/ci_macos_deps.sh Debug 17
      - name: Build
        run: ./ci_scripts/ci_macos_build.sh Debug
      - name: Test
        run: ./ci_scripts/ci_macos_test.sh Debug
  release17:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: ./ci_scripts/ci_macos_deps.sh Release 17
      - name: Build
        run: ./ci_scripts/ci_macos_build.sh Release
      - name: Test
        run: ./ci_scripts/ci_macos_test.sh Release
  debug20:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: ./ci_scripts/ci_macos_deps.sh Debug 20
      - name: Build
        run: ./ci_scripts/ci_macos_build.sh Debug
      - name: Test
        run: ./ci_scripts/ci_macos_test.sh Debug
  release20:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: ./ci_scripts/ci_macos_deps.sh Release 20
      - name: Build
        run: ./ci_scripts/ci_macos_build.sh Release
      - name: Test
        run: ./ci_scripts/ci_macos_test.sh Release

