name: MacOS

on:
  push:
    branches: [release, develop]
  pull_request:
        push:
          branches-ignore: develop
    pull_request:
      branches-ignore: develop

jobs:
  debug:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: ./ci_scripts/ci_macos_deps.sh Debug
      - name: Build
        run: ./ci_scripts/ci_macos_build.sh Debug
      - name: Test
        run: ./ci_scripts/ci_macos_test.sh Debug
  release:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: ./ci_scripts/ci_macos_deps.sh Release
      - name: Build
        run: ./ci_scripts/ci_macos_build.sh Release
      - name: Test
        run: ./ci_scripts/ci_macos_test.sh Release

