name: Ubuntu

on:
  push:
    branches: release
  pull_request:
    push:
      branches-ignore: dev
    pull_request:
      branches-ignore: dev        

jobs:
  debug:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Add LLVM Repo
      run: sudo sh ./ci_scripts/ci_ubuntu_install_clang.sh
    - name: Download & Build Dependencies
      run: |        
        sudo apt update
        sudo apt install clang-9 libc++-9-dev libc++abi-9-dev
    - name: Build Dependencies
      run: ./ci_scripts/ci_ubuntu_deps.sh Debug
    - name: Build
      run: ./ci_scripts/ci_ubuntu_build.sh Debug
    - name: Test
      run: ./ci_scripts/ci_ubuntu_test.sh Debug
  release:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Add LLVM Repo
        run: sudo sh ./ci_scripts/ci_ubuntu_install_clang.sh
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install clang-9 libc++-9-dev libc++abi-9-dev
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Release
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Release
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Release

