name: Ubuntu(clang/libc++)

on:
  push:
    branches: [release, develop]
  pull_request:
    push:
      branches-ignore: develop
    pull_request:
      branches-ignore: develop        

jobs:
  debug17:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Add LLVM Repo
      run: sudo sh ./ci_scripts/ci_ubuntu_install_clang.sh
    - name: Download & Build Dependencies
      run: |        
        sudo apt update
        sudo apt install clang-12 libc++-12-dev libc++abi-12-dev libunwind-dev 
    - name: Build Dependencies
      run: ./ci_scripts/ci_ubuntu_deps.sh Debug 17 clang-12 clang++-12 -stdlib=libc++
    - name: Build
      run: ./ci_scripts/ci_ubuntu_build.sh Debug
    - name: Test
      run: ./ci_scripts/ci_ubuntu_test.sh Debug
  release17:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Add LLVM Repo
        run: sudo sh ./ci_scripts/ci_ubuntu_install_clang.sh
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install clang-12 libc++-12-dev libc++abi-12-dev libunwind-dev
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Release 17 clang-12 clang++-12 -stdlib=libc++ 
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Release
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Release
      - name: Run fuzz test
        run: ./ci_scripts/ci_ubuntu_fuzz.sh
  debug20:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Add LLVM Repo
        run: sudo sh ./ci_scripts/ci_ubuntu_install_clang.sh
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install clang-12 libc++-12-dev libc++abi-12-dev libunwind-dev
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Debug 20 clang-12 clang++-12 -stdlib=libc++
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Debug
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Debug
      - name: Archive any crashes as an artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: crashes
          path: |
            crash-*
            leak-*
            timeout-*
          if-no-files-found: ignore
  release20:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Add LLVM Repo
        run: sudo sh ./ci_scripts/ci_ubuntu_install_clang.sh
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install clang-12 libc++-12-dev libc++abi-12-dev libunwind-dev
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Release 20 clang-12 clang++-12 -stdlib=libc++
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Release
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Release
      - name: Run fuzz test
        run: ./ci_scripts/ci_ubuntu_fuzz.sh
      - name: Archive any crashes as an artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: crashes
          path: |
            crash-*
            leak-*
            timeout-*
          if-no-files-found: ignore

