name: Ubuntu

on:
  pull_request:
    push:
      branches-ignore: dev
    pull_request:
      branches-ignore: dev

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Add LLVM Repo
      run: sudo sh ./ci_scripts/ci_ubuntu_install_clang.sh
    - name: Download & Build Dependencies
      run: |        
        sudo apt update
        sudo apt install clang-9 libc++-9-dev libc++abi-9-dev
    - name: Build Dependencies
      run: ./ci_scripts/ci_ubuntu_deps.sh  
    - name: Build
      run: ./ci_scripts/ci_ubuntu_build.sh
    - name: Test
      run: ./ci_scripts/ci_ubuntu_test.sh
       
