name: Ubuntu(gcc)

on:
  push:
    branches: [release, develop]
  pull_request:
    push:
      branches-ignore: develop
    pull_request:
      branches-ignore: develop        

jobs:
  debug17:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Download & Build Dependencies
      run: |        
        sudo apt update
        sudo apt install gcc-10 g++-10
    - name: Build Dependencies
      run: ./ci_scripts/ci_ubuntu_deps.sh Debug 17 gcc-10 g++-10
    - name: Build
      run: ./ci_scripts/ci_ubuntu_build.sh Debug
    - name: Test
      run: ./ci_scripts/ci_ubuntu_test.sh Debug
  release17:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Release 17 gcc-10 g++-10
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Release
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Release
  debug20:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Debug 20 gcc-10 g++-10
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Debug
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Debug
  release20:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Release 20 gcc-10 g++-10
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Release
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Release


