name: Ubuntu

on:
  push:
    branches: [ release, develop ]
  pull_request:
    push:
      branches-ignore: develop
    pull_request:
      branches-ignore: develop

jobs:
  ubuntu2004_clang12_debug_17:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v1
      - name: Add LLVM Repo
        run: sudo sh ./ci_scripts/ci_ubuntu_install_clang.sh
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install clang-12 libc++-12-dev libc++abi-12-dev libunwind-dev
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Debug 17 clang-12 clang++-12
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Debug
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Debug
  ubuntu2004_clang_release_17:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v1
      - name: Add LLVM Repo
        run: sudo sh ./ci_scripts/ci_ubuntu_install_clang.sh
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install clang-12 libc++-12-dev libc++abi-12-dev libunwind-dev
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Release 17 clang-12 clang++-12
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Release
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Release
      - name: Run fuzz test
        run: ./ci_scripts/ci_ubuntu_fuzz.sh
  ubuntu2004_clang_debug_20:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v1
      - name: Add LLVM Repo
        run: sudo sh ./ci_scripts/ci_ubuntu_install_clang.sh
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install clang-12 libc++-12-dev libc++abi-12-dev libunwind-dev
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Debug 20 clang-12 clang++-12
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Debug
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Debug
      - name: Archive any crashes as an artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: crashes
          path: |
            crash-*
            leak-*
            timeout-*
          if-no-files-found: ignore
  ubuntu2004_clang_release_20:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v1
      - name: Add LLVM Repo
        run: sudo sh ./ci_scripts/ci_ubuntu_install_clang.sh
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install clang-12 libc++-12-dev libc++abi-12-dev libunwind-dev
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Release 20 clang-12 clang++-12
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Release
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Release
      - name: Run fuzz test
        run: ./ci_scripts/ci_ubuntu_fuzz.sh
      - name: Archive any crashes as an artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: crashes
          path: |
            crash-*
            leak-*
            timeout-*
          if-no-files-found: ignore
  ubuntu2004_gcc10_debug_17:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v1
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Debug 17 gcc-10 g++-10
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Debug
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Debug
  ubuntu2004_gcc10_release_17:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v1
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Release 17 gcc-10 g++-10
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Release
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Release
  ubuntu2004_gcc10_debug_20:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v1
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Debug 20 gcc-10 g++-10
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Debug
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Debug
  ubuntu2004_gcc10_release_20:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v1
      - name: Download & Build Dependencies
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
      - name: Build Dependencies
        run: ./ci_scripts/ci_ubuntu_deps.sh Release 20 gcc-10 g++-10
      - name: Build
        run: ./ci_scripts/ci_ubuntu_build.sh Release
      - name: Test
        run: ./ci_scripts/ci_ubuntu_test.sh Release
