name: Windows

on:
  push:
    branches-ignore: dev
  pull_request:
    branches-ignore: dev
    

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Run CMake
        working-directory: build
        run: cmake.exe ..
        shell: cmd
      - name: Build
        working-directory: build 
        run: cmake.exe --build . --config Debug --target full -j 2
        shell: cmd
      - name: Test
        working-directory: build
        run: ctest.exe -C Debug
        shell: cmd
