name: Windows

on:
  push:
    branches: [release, develop]
  pull_request:
    push:
      branches-ignore: develop
    pull_request:
      branches-ignore: develop

jobs:
  debug17:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: .\ci_scripts\ci_windows_deps.cmd Debug 17
      - name: Build
        run: .\ci_scripts\ci_windows_build.cmd Debug
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd Debug
  release17:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: .\ci_scripts\ci_windows_deps.cmd Release 17
      - name: Build
        run: .\ci_scripts\ci_windows_build.cmd Release
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd Release
  debug20:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: .\ci_scripts\ci_windows_deps.cmd Debug 20
      - name: Build
        run: .\ci_scripts\ci_windows_build.cmd Debug
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd Debug
  release20:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: .\ci_scripts\ci_windows_deps.cmd Release 20
      - name: Build
        run: .\ci_scripts\ci_windows_build.cmd Release
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd Release
