name: Windows

on:
  push:
    branches: release
  pull_request:
    push:
      branches-ignore: develop
    pull_request:
      branches-ignore: develop

jobs:
  debug:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: .\ci_scripts\ci_windows_deps.cmd Debug
      - name: Build
        run: .\ci_scripts\ci_windows_build.cmd Debug
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd Debug
  release:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: .\ci_scripts\ci_windows_deps.cmd Release
      - name: Build
        run: .\ci_scripts\ci_windows_build.cmd Release
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd Release
