name: Windows

on:
  push:
    branches-ignore: dev
  pull_request:
    branches-ignore: dev
    

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Run CMake
        working-directory: build
        run: cmake 
      - name: Build
        working-directory: build ${{ GITHUB_WORKSPACE }}/daw_json_link
        run: cmake --build . --config Debug --target full -j 2
      - name: Test
        working-directory: build
        run: ctest -C Debug
