name: Windows2019

on:
  push:
    branches: [ release, develop ]
  pull_request:
    push:
      branches-ignore: develop
    pull_request:
      branches-ignore: develop

jobs:
  windows2019_msvc2019_debug_17:
    runs-on: [ windows-2019 ]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: .\ci_scripts\ci_windows_deps.cmd Debug 17
      - name: Build
        run: .\ci_scripts\ci_windows_build.cmd Debug
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd Debug
  windows2019_msvc2019_release_17:
    runs-on: [ windows-2019 ]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: .\ci_scripts\ci_windows_deps.cmd Release 17
      - name: Build
        run: .\ci_scripts\ci_windows_build.cmd Release
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd Release
  windows2019_msvc2019_debug_20:
    runs-on: [ windows-2019 ]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: .\ci_scripts\ci_windows_deps.cmd Debug 20
      - name: Build
        run: .\ci_scripts\ci_windows_build.cmd Debug
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd Debug
  windows2019_msvc2019_release_20:
    runs-on: [ windows-2019 ]
    steps:
      - uses: actions/checkout@v1
      - name: Build Dependencies
        run: .\ci_scripts\ci_windows_deps.cmd Release 20
      - name: Build
        run: .\ci_scripts\ci_windows_build.cmd Release
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd Release
  windows2019_clangcl_debug_17:
    runs-on: [ windows-2019 ]
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: .\ci_scripts\ci_windows_build_clangcl.cmd Debug 17
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd
  windows2019_clangcl_release_17:
    runs-on: [ windows-2019 ]
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: .\ci_scripts\ci_windows_build_clangcl.cmd Release 17
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd
  windows2019_clangcl_debug_20:
    runs-on: [ windows-2019 ]
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: .\ci_scripts\ci_windows_build_clangcl.cmd Debug 20
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd
  wwindows2019_clangcl_release_20:
    runs-on: [ windows-2019 ]
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: .\ci_scripts\ci_windows_build_clangcl.cmd Release 20
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd
