name: clang-format Check
on: 
  push:
    branches: release
  pull_request:
    push:
      branches-ignore: develop
    pull_request:
      branches-ignore: develop


jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C programs.
      uses: jidicula/clang-format-action@master
