name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download & Build Dependencies
      run: |
        sudo apt update
        sudo apt install libboost-all-dev libcurl4-dev
    - name: Run make_deps
      run: ./make_deps.sh
    - name: Configure
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=Debug ..
    - name: Build project
      working-directory: build      
      run: cmake --build . --config Debug -j 2
    - name: Test
      working-directory: build      
      run: ctest
